#pragma once
#include <Arduino.h>
#include <string.h>

// Traduccion de la interfaz. Los literales del codigo estan en castellano y
// sirven como clave; lang::tr() devuelve la version inglesa cuando el idioma
// activo es ingles (por defecto) y el propio literal cuando es castellano.
//
// Solo hay una unidad de traduccion (NativeApp.cpp incluye este fichero), asi
// que el estado puede vivir como static en la cabecera.

namespace lang {

enum class Lang : uint8_t { EN = 0, ES = 1 };

static Lang gLang = Lang::EN;

inline Lang current() { return gLang; }
inline void set(Lang l) { gLang = l; }

struct Entry { const char* es; const char* en; };

inline const char* tr(const char* es) {
  if (gLang == Lang::ES) return es;
  static const Entry kT[] = {
    // Menu principal
    {"SEED WORKSTATION", "Seed workstation"},
    {"Semilla activa en memoria", "Active seed in memory"},
    {"Sin semilla cargada", "No seed loaded"},
    {"INTRODUCIR SEMILLA", "Enter seed"},
    {"GENERAR ENTROPIA", "Generate entropy"},
    {"VAULT DE SESION", "Session vault"},
    {"AYUDA", "Help"},
    {"RECIBIR POR WIFI", "Receive via WiFi"},
    {"BLOQUEAR", "Lock"},
    {"SEMILLA ACTIVA", "Active seed"},

    // Comunes
    {"VOLVER", "Back"},
    {"CANCELAR", "Cancel"},
    {"ERROR", "Error"},
    {"CONTINUAR", "Continue"},
    {"OK", "OK"},
    {"REINTENTAR", "Retry"},
    {"MENU SEED", "Seed menu"},
    {"CREAR SEMILLA", "Create seed"},
    {"VER QR", "View QR"},
    {"SIGUIENTE", "Next"},
    {"ANTERIOR", "Previous"},
    {"24 PALABRAS", "24 words"},
    {"12 PALABRAS", "12 words"},
    {"FIRMAR", "Sign"},
    {"CARGAR SEMILLA", "Load seed"},
    {"CAMBIO", "Change"},
    {"BLOQUEAR VAULT", "Lock vault"},
    {"BACKUP SEEDQR", "SeedQR backup"},
    {"VER PALABRAS", "View words"},
    {"VAULT SEGURO", "Secure vault"},
    {"TIRAR DADOS", "Roll dice"},
    {"REINICIAR", "Reset"},
    {"RECIBIR", "Receive"},
    {"QR DIRECCION", "Address QR"},
    {"MOSTRAR 3 SEG.", "Show 3 s."},
    {"GUARDAR", "Save"},
    {"DETALLE", "Details"},
    {"DESBLOQUEAR VAULT", "Unlock vault"},
    {"ACTIVAR", "Activate"},
    {"ACCIONES EN VAULT", "Vault actions"},
    {"ABRIR VAULT", "Open vault"},
    {"VISIBLE 3 SEG.", "Visible 3 s."},
    {"MODO ELIMINAR", "Delete mode"},
    {"IR A INDICE", "Go to index"},
    {"CANCELAR ELIMINACION", "Cancel delete"},
    {"BACKUP SEED", "Seed backup"},
    {"DESBLOQUEAR", "Unlock"},
    {"BORRAR", "Delete"},
    {"GUARDAR SEMILLA ACTIVA", "Save active seed"},
    {"GUARDAR EN VAULT", "Save to vault"},
    {"GUARDAR CIFRADO", "Save encrypted"},
    {"ELIMINAR ARCHIVO", "Delete file"},
    {"DESCARTAR SEED", "Discard seed"},
    {"CREAR VAULT", "Create vault"},
    {"CONFIRMAR DESCARTE", "Confirm discard"},
    {"CERRAR VAULT", "Close vault"},
    {"CARGAR SOLO EN RAM", "Load RAM only"},
    {"CARGAR NUEVA SEED", "Load new seed"},
    {"ACTIVAR EN RAM", "Activate in RAM"},
    {"ABRIR SEMILLA", "Open seed"},
    {"MOSTRAR QR", "Show QR"},
    {"ULTIMA", "Last"},
    {"SALIR", "Exit"},
    {"REVISAR", "Review"},
    {"VOLVER AL MENU", "Back to menu"},
    {"VOLVER AL MENU SEED", "Back to seed menu"},
    {"VOLVER AL EXPLORADOR", "Back to explorer"},
    {"VOLVER A CLAVE", "Back to key"},
    {"ELIMINAR VAULT", "Delete vault"},
    {"ELIMINAR SEMILLA", "Delete seed"},
    {"ANADIR", "Add"},
    {"ABRIR VAULT DE SESION", "Open session vault"},
    {"CONFIRMAR ELIMINACION", "Confirm delete"},
    {"NUEVO VAULT", "New vault"},
    {"NUEVA SEMILLA", "New seed"},
    {"VER CLAVE PUBLICA", "View public key"},
    {"EXPLORAR DIRECCIONES", "Explore addresses"},
    {"QUITAR PASSPHRASE", "Remove passphrase"},
    {"BIP39 PASSPHRASE", "BIP39 passphrase"},
    {"EMITIR", "Broadcast"},
    {"PAGO", "Payment"},
    {"Cambio", "Change"},
    {"NO USAR FONDOS REALES (DEV)", "NO REAL FUNDS (DEV)"},

    // Pantallas
    {"LONGITUD", "Length"},
    {"Elige el numero de palabras", "Choose the number of words"},
    {"Elige la longitud BIP39", "Choose BIP39 length"},
    {"DIBUJA ENTROPIA", "Draw entropy"},
    {"Traza movimientos largos e irregulares", "Trace long, irregular movements"},
    {"Entropia con dados fisicos 1-6", "Entropy with physical dice 1-6"},
    {"Toca la cara del dado que ha salido", "Tap the face of the die you rolled"},
    {"REVISION", "Review"},
    {"Toca una palabra para corregirla", "Tap a word to correct it"},
    {"Semilla nueva para el Vault de sesion", "New seed for the session vault"},
    {"Semilla nueva que quedara solo en RAM", "New seed that stays in RAM only"},
    {"Acciones disponibles en memoria", "Actions available in memory"},
    {"SEMILLAS EN MEMORIA", "Seeds in memory"},
    {"Selecciona la semilla activa", "Select the active seed"},
    {"Copias y comprobacion de la semilla", "Seed copies and verification"},
    {"CLAVE PUBLICA", "Public key"},
    {"Calculando y verificando derivacion...", "Computing and verifying derivation..."},
    {"CLAVE PUBLICA - DATOS SENSIBLES", "Public key - sensitive data"},
    {"DIRECCIONES", "Addresses"},
    {"Rama: %s", "Branch: %s"},
    {"Ruta: %s/%u/%lu", "Path: %s/%u/%lu"},
    {"Toca el indice para ir a uno concreto (0-999999)", "Tap the index to jump to a specific one (0-999999)"},
    {"Escribe el numero de indice (0-999999)", "Type the index number (0-999999)"},
    {"Escribe 4 letras y toca la palabra", "Type 4 letters and tap the word"},
    {"TECLADO BIP39", "BIP39 keyboard"},
    {"Coincidencias: %u", "Matches: %u"},
    {"Checksum BIP39 valido", "Valid BIP39 checksum"},
    {"INCOMPLETA", "Incomplete"},
    {"VALIDO", "Valid"},
    {"INVALIDO", "Invalid"},
    {"Checksum: %s", "Checksum: %s"},
    {"DIAGNOSTICO", "Diagnostics"},
    {"Controlador nativo M5EPD", "Native M5EPD driver"},
    {"Pantalla: 540 x 960", "Screen: 540 x 960"},
    {"Tactil GT911: activo", "GT911 touch: active"},
    {"Refresco: Canvas A2 / DU4", "Refresh: Canvas A2 / DU4"},
    {"microSD: %s", "microSD: %s"},
    {"Conceptos basicos", "Basics"},
    {"TRANSACCION", "Transaction"},
    {"PSBT sin firmar - verifica con calma", "Unsigned PSBT - verify carefully"},
    {"Entradas: %u   Salidas: %u", "Inputs: %u   Outputs: %u"},
    {"Total a gastar: %s BTC", "Total to spend: %s BTC"},
    {"Pago: %s BTC", "Payment: %s BTC"},
    {"Cambio: %s BTC", "Change: %s BTC"},
    {"Cambio: no marcado", "Change: not marked"},
    {"Comision: %s BTC", "Fee: %s BTC"},
    {"Comprueba tu direccion de cambio", "Check your change address"},
    {"... y %u salidas mas", "... and %u more outputs"},
    {"UTXOS (ENTRADAS)", "UTXOs (inputs)"},
    {"De donde salen los fondos", "Where the funds come from"},
    {"#%u  %s BTC", "#%u  %s BTC"},
    {"... y %u entradas mas", "... and %u more inputs"},
    {"direccion no estandar", "non-standard address"},
    {"direccion no disponible", "address not available"},
    {"TX FIRMADA", "Signed TX"},
    {"Escanear con Sparrow para emitir", "Scan with Sparrow to broadcast"},
    {"Escanea el QR animado (BBQr)", "Scan the animated QR (BBQr)"},
    {"Elige el metodo de salida", "Choose the output method"},
    {"SPARROW (QR estatico)", "Sparrow (static QR)"},
    {"BLUEWALLET (QR animado)", "BlueWallet (animated QR)"},
    {"RECIBIDO", "Received"},
    {"Datos recibidos por WiFi", "Data received via WiFi"},
    {"SEMILLA NO VALIDA", "Invalid seed"},
    {"No se pudo importar la semilla", "Could not import the seed"},
    {"Revisa las palabras y que sean 12 o 24.", "Check the words; they must be 12 or 24."},
    {"No se pudo activar el punto de acceso", "Could not start the access point"},
    {"No se pudo crear la red WiFi.", "Could not create the WiFi network."},
    {"Elige que vas a enviar", "Choose what you will send"},
    {"Subir fichero PSBT", "Upload PSBT file"},
    {"Pegar transaccion", "Paste transaction"},
    {"Pegar semilla BIP39", "Paste BIP39 seed"},
    {"Conectate y sube el fichero PSBT desde la web", "Connect and upload the PSBT file from the web page"},
    {"Conectate y pega la transaccion en la web", "Connect and paste the transaction on the web page"},
    {"Conectate y pega la semilla BIP39 en la web", "Connect and paste the BIP39 seed on the web page"},
    {"BLOQUEADO", "Locked"},
    {"Bloqueado", "Locked"},
    {"Pulsa o toca para desbloquear", "Press or tap to unlock"},
    {"SEGURIDAD", "Security"},
    {"COMPRUEBA TU ENTORNO", "Check your surroundings"},
    {"Evita camaras y ventanas.", "Avoid cameras and windows."},
    {"Comprueba que estas solo.", "Make sure you are alone."},
    {"No permitas fotos de la pantalla.", "Do not allow photos of the screen."},
    {"Vas a mostrar datos sensibles.", "You are about to show sensitive data."},
    {"ESTOY EN UN LUGAR SEGURO", "I am in a safe place"},
    {"VAULT GUARDADO Y VERIFICADO", "Vault saved and verified"},
    {"Copia cifrada terminada", "Encrypted copy complete"},
    {"VAULT RECUPERADO", "Vault recovered"},
    {"VAULT VACIO", "Vault empty"},
    {"SEMILLAS DEL VAULT", "Seeds in the vault"},
    {"Selecciona una copia cifrada de la SD", "Select an encrypted copy from the SD"},
    {"Selecciona el Vault que quieres abrir", "Select the vault you want to open"},
    {"Selecciona el archivo que quieres borrar", "Select the file you want to delete"},
    {"Selecciona el registro que quieres borrar", "Select the record you want to delete"},
    {"NO HAY ARCHIVOS .VLT", "No .VLT files"},
    {"NO HAY VAULTS DE SESION", "No session vaults"},
    {"SD NO DETECTADA", "SD card not detected"},
    {"NO SE DETECTA LA TARJETA SD", "No SD card detected"},
    {"CONTRASENA INCORRECTA O ARCHIVO ALTERADO", "Wrong password or tampered file"},
    {"YA EXISTE UN VAULT PARA ESTA SEED", "A vault already exists for this seed"},
    {"ETIQUETA VAULT", "Vault label"},
    {"ETIQUETA SEMILLA", "Seed label"},
    {"Nombre reconocible para la copia cifrada", "Recognizable name for the encrypted copy"},
    {"Nombre reconocible dentro del Vault", "Recognizable name within the vault"},
    {"Nombre del Vault de sesion", "Session vault name"},
    {"1-16 letras. Ejemplos:", "1-16 letters. Examples:"},
    {"ahorro, viajes o casa", "savings, trips or home"},
    {"Crea una contrasena para la SD", "Create a password for the SD"},
    {"Minimo 12 letras. No podremos recuperarla.", "At least 12 letters. We cannot recover it."},
    {"No se guardara. 'Casa' y 'casa' son distintas.", "It won't be saved. 'Casa' and 'casa' are different."},
    {"Las mayusculas importan (ASCII)", "Uppercase matters (ASCII)"},
    {"Repite la contrasena", "Repeat the password"},
    {"Repite EXACTAMENTE: mayusculas incluidas", "Repeat EXACTLY, including uppercase"},
    {"NO COINCIDEN: repite la segunda contrasena.", "They do NOT match: repeat the second password."},
    {"NO COINCIDEN. REPITE LA CONFIRMACION.", "They do NOT match. Repeat the confirmation."},
    {"Introduce la contrasena del Vault", "Enter the vault password"},
    {"Descifrando y verificando...", "Decrypting and verifying..."},
    {"Derivando clave (PBKDF2)...", "Deriving key (PBKDF2)..."},
    {"Derivando la clave maestra", "Deriving the master key"},
    {"Derivando la clave maestra (PBKDF2).", "Deriving the master key (PBKDF2)."},
    {"Puede tardar varios segundos.", "It may take a few seconds."},
    {"Puede tardar. No retires la tarjeta.", "May take a while. Do not remove the card."},
    {"No retires la tarjeta SD.", "Do not remove the SD card."},
    {"Cifrando y verificando la tarjeta SD...", "Encrypting and verifying the SD card..."},
    {"Creando vault seguro...", "Creating secure vault..."},
    {"Creando vault seguro", "Creating secure vault"},
    {"ERROR DE ESCRITURA EN LA SD", "Error writing to SD"},
    {"ERROR CRIPTOGRAFICO", "Crypto error"},
    {"FALLO DE VERIFICACION", "Verification failed"},
    {"ELIMINAR ARCHIVO", "Delete file"},
    {"ELIMINAR VAULT", "Delete vault"},
    {"ELIMINAR SEMILLA", "Delete seed"},
    {"Se eliminara de la tarjeta SD:", "This will be removed from the SD card:"},
    {"El archivo existente", "The existing file"},
    {"no se ha sobrescrito.", "has not been overwritten."},
    {"No se pudo borrar el archivo", "Could not delete the file"},
    {"No se pudo firmar", "Could not sign"},
    {"ERROR DE FIRMA", "Signing error"},
    {"Operacion no completada", "Operation not completed"},
    {"Transaccion firmada y guardada en la SD", "Transaction signed and saved to SD"},
    {"No se puede deshacer.", "This cannot be undone."},
    {"Esta operacion no se puede deshacer", "This operation cannot be undone"},
    {"Esta accion elimina la semilla de RAM", "This action removes the seed from RAM"},
    {"Hay una semilla activa en RAM", "There is an active seed in RAM"},
    {"Hay una passphrase activa en RAM.", "There is an active passphrase in RAM."},
    {"La semilla activa no se descarta.", "The active seed is not discarded."},
    {"La semilla sigue activa en memoria.", "The seed stays active in memory."},
    {"La semilla activa se conservara.", "The active seed will be kept."},
    {"Si no esta guardada, se perdera.", "If it is not saved, it will be lost."},
    {"Al abrir el vault se descartara", "Opening the vault will discard"},
    {"la semilla que esta activa ahora.", "the seed that is currently active."},
    {"PASSPHRASE ACTIVA", "Passphrase active"},
    {"PASSPHRASE QUITADA", "Passphrase removed"},
    {"PASSPHRASE: ACTIVA EN RAM", "Passphrase: active in RAM"},
    {"SEED SOLO EN RAM - NO EN VAULT", "Seed in RAM only - not in vault"},
    {"Toca el FINGERPRINT para cambiar de semilla", "Tap the FINGERPRINT to switch seed"},
    {"SIN ETIQUETA", "No label"},
    {"[RAM]", "[RAM]"},
    {"%u palabras cargadas en memoria", "%u words loaded in memory"},
    {"QR limpio de la semilla activa", "Clean QR of the active seed"},
    {"Semillas cargadas en RAM: %u\n", "Seeds loaded in RAM: %u\n"},
    {"Sesion activa: %s", "Active session: %s"},
    {"Registro de sesion invalido omitido: %s\n", "Invalid session record skipped: %s\n"},
    {"Mainnet  %s", "Mainnet  %s"},
    {"BIP86 conserva prefijo xpub: la ruta identifica Taproot.", "BIP86 keeps the xpub prefix: the path identifies Taproot."},
    {"Escribe una semilla BIP39 palabra a palabra", "Enter a BIP39 seed word by word"},
    {"Genera una semilla aleatoria con entropia propia", "Generate a random seed with your own entropy"},
    {"Cifra y guarda varias semillas bajo una contrasena maestra", "Encrypt and store several seeds under a master password"},
    {"Conceptos basicos y glosario", "Basics and glossary"},
    {"Recibe un archivo o QR por WiFi desde tu movil", "Receive a file or QR via WiFi from your phone"},
    {"Carga una semilla para poder recibir y firmar", "Load a seed to receive and sign"},
    {"Bloquea el dispositivo y muestra la portada", "Lock the device and show the cover"},
    {"Abre el menu de la semilla que ya esta activa", "Open the menu of the seed that is active"},
    {"Descarta la semilla activa para crear otra", "Discard the active seed to create another"},
    {"Deriva la clave publica (xpub/zpub) para ver solo direcciones", "Derive the public key (xpub/zpub) to view addresses only"},
    {"Copia y comprueba la semilla (palabras, QR o SEEDQR)", "Copy and verify the seed (words, QR or SeedQR)"},
    {"Anade una passphrase BIP39 (cambia todas las direcciones)", "Add a BIP39 passphrase (changes all addresses)"},
    {"Deriva direcciones concretas para recibir o para cambio", "Derive specific addresses to receive or for change"},
    {"Cargar o guardar semillas en el vault de sesion", "Load or save seeds in the session vault"},
    {"Borra la semilla de la memoria RAM", "Erase the seed from RAM"},
    {"Recibe un PSBT o archivo por WiFi para firmar", "Receive a PSBT or file via WiFi to sign"},
    {"Recibe un PSBT o una semilla por WiFi desde tu movil", "Receive a PSBT or a seed via WiFi from your phone"},
    {"Recibe una semilla BIP39 por texto desde tu movil", "Receive a BIP39 seed by text from your phone"},
    {"Cierra el vault y borra la clave maestra de RAM", "Close the vault and erase the master key from RAM"},
    {"Sustituir palabra %u de %u", "Replace word %u of %u"},
    {"Palabra %u de %u", "Word %u of %u"},
    {"FILA %02u/%02u   PASO %02u/%02u", "ROW %02u/%02u   STEP %02u/%02u"},
    {"Asistente de dibujo fila a fila", "Row-by-row drawing wizard"},
    {"Backup SEEDQR", "SeedQR backup"},
    {"Backup SEEDQR", "SeedQR backup"},

    // Serial / WiFi / BLE
    {"PSBT recibido por serial", "PSBT received via serial"},
    {"Serial: no es un PSBT valido", "Serial: not a valid PSBT"},
    {"Serial: SHA256 no coincide", "Serial: SHA256 mismatch"},
    {"QR SCANNER", "QR scanner"},
    {"Recibiendo el QR...", "Receiving the QR..."},
    {"Esperando QR...", "Waiting for QR..."},
    {"Buscando camara...", "Looking for camera..."},
    {"Camara escaneando...", "Camera scanning..."},
    {"Camara encontrada. Conectando...", "Camera found. Connecting..."},
    {"Camara conectada. Esperando QR...", "Camera connected. Waiting for QR..."},
    {"Camara desconectada", "Camera disconnected"},
    {"Conectando...", "Connecting..."},
    {"No se encontro la camara", "Camera not found"},
    {"No se pudo conectar", "Could not connect"},
    {"No se pudo suscribir", "Could not subscribe"},
    {"La camara no ha podido entregar el QR.", "The camera could not deliver the QR."},
    {"La transferencia ha fallado", "The transfer failed"},
    {"Transferencia completada", "Transfer complete"},
    {"Transferencia agotada", "Transfer timed out"},
    {"TRANSFERENCIA INVALIDA", "Invalid transfer"},
    {"PAYLOAD DEMASIADO GRANDE", "Payload too large"},
    {"Error de inicializacion BLE", "BLE initialization error"},
    {"Servicio BLE no encontrado", "BLE service not found"},
    {"QR detectado", "QR detected"},
    {"Manten el movil quieto", "Hold the phone still"},
    {"Iniciando transferencia...", "Starting transfer..."},
    {"Desbloqueando...", "Unlocking..."},

    // Radio / ajustes
    {"AJUSTES", "Settings"},
    {"Configuracion del dispositivo", "Device settings"},
    {"Radios y energia", "Radios and power"},
    {"Idioma, bloqueo, derivacion y estado de la radio", "Language, lock, derivation and radio status"},
    {"microSD", "microSD"},
    {"Idioma", "Language"},
    {"Elige el idioma de la interfaz", "Choose the interface language"},
    {"Ingles", "English"},
    {"Espanol", "Spanish"},
    {"Tiempo de bloqueo", "Lock timeout"},
    {"Bloqueo automatico por inactividad", "Automatic lock on inactivity"},
    {"Nunca", "Never"},
    {"1 minuto", "1 minute"},
    {"3 minutos", "3 minutes"},
    {"5 minutos", "5 minutes"},
    {"10 minutos", "10 minutes"},
    {"Derivacion por defecto", "Default derivation"},
    {"Tipo de direccion al abrir", "Address type on open"},
    {"Estado de la radio", "Radio status"},
    {"Bluetooth", "Bluetooth"},
    {"WiFi", "WiFi"},
    {"APAGADO", "Off"},
    {"ACTIVO", "On"},
    {"ESCANEANDO", "Scanning"},
    {"PUNTO DE ACCESO", "Access point"},
    {"Bateria", "Battery"},
    {"Guardado en la SD", "Saved to SD"},
    {"No se pudo guardar la configuracion", "Could not save the configuration"},
    {"Tarjeta SD no disponible", "SD card not available"},
    {"BIP44 (P2PKH)", "BIP44 (P2PKH)"},
    {"BIP49 (P2SH)", "BIP49 (P2SH)"},
    {"BIP84 (SegWit)", "BIP84 (SegWit)"},
    {"BIP86 (Taproot)", "BIP86 (Taproot)"},
    {"Tipo de script", "Script type"},

    // Perfiles
    {"Legacy P2PKH", "Legacy P2PKH"},
    {"SegWit anidado P2SH", "Nested SegWit P2SH"},
    {"Native SegWit", "Native SegWit"},
    {"Taproot P2TR", "Taproot P2TR"},

    // Sueltos
    {"Mezcla: %u/%u | RNG: %s", "Mix: %u/%u | RNG: %s"},
    {"Lanzamientos: ", "Rolls: "},
    {"AES-256-GCM / clave de sesion", "AES-256-GCM / session key"},
    {"Archivo: ", "File: "},
    {"Se bloqueara en ", "Will lock in "},
    {"Toca la pantalla o pulsa", "Tap the screen or press"},
    {"la palanca para continuar.", "the lever to continue."},
    {"Revela direcciones e historial.", "Reveals addresses and history."},
    {"No permite gastar.", "Does not allow spending."},
    {"ERROR DE DERIVACION", "Derivation error"},
    {"Comprueba el fingerprint", "Check the fingerprint"},
    {"antes de continuar.", "before continuing."},
    {"Clave: ", "Key: "},
    {"Modo: ", "Mode: "},
    {"Columnas ", "Columns "},
    {"Casillas ", "Boxes "},
    {"Casilla ", "Box "},
    {"Columnas", "Columns"},
    {"NEGRAS", "Black"},
    {"BLANCAS", "White"},
    {"NEGRA", "Black"},
    {"BLANCA", "White"},
    {"ESPACIO", "Space"},
    {"OCULTAR", "Hide"},
    {"MOSTRAR", "Show"},
    {"RAM", "RAM"},
    {"ACTIVA", "Active"},
    {"Bloqueado", "Locked"},

    // Ayuda
    {"VAULT DE SESION: varias semillas cifradas", "Session vault: several seeds encrypted"},
    {"bajo una unica contrasena maestra.", "under a single master password."},
    {"VAULT INDIVIDUAL: una sola semilla cifrada", "Individual vault: a single seed encrypted"},
    {"con su propia contrasena (archivo .vlt).", "with its own password (.vlt file)."},
    {"SOLO RAM: la semilla no se guarda y se", "RAM only: the seed is not saved and is"},
    {"borra al apagar o al descartarla.", "erased on shutdown or when discarded."},
    {"PASSPHRASE: palabra extra (BIP39) que", "Passphrase: an extra word (BIP39) that"},
    {"cambia TODAS tus direcciones.", "changes ALL your addresses."},
    {"FINGERPRINT: identificador corto de tu", "Fingerprint: a short identifier of your"},
    {"semilla para verificarla visualmente.", "seed to verify it visually."},
    {"ENTROPIA: aleatoriedad que genera la", "Entropy: the randomness that generates the"},
    {"semilla dibujando o tirando dados.", "seed by drawing or rolling dice."},
  };

  for (const auto& e : kT) {
    if (strcmp(e.es, es) == 0) return e.en;
  }
  return es;
}

}  // namespace lang
